### PR TITLE
props.children + autobind

### PR DESCRIPTION
**Pull request by developit**
Update to Preact 4.8.0 to fix `props.children`, and add auto-binding to `createComponent()`.
This gets me to:

### CODE REVIEW

**Comment by ld0rman** [comment]
Weird, I tried to do this locally as well and encountered the same problem - npm says that 4.8.0 isn't published. The registry site seems to say the same thing. Did you do like a local publish or something? 

Nice upgrade of the createComponent function btw

**Comment by developit** [comment]
@ld0rman Wow, I must not have had my brain turned on yesterday. I published 4.8.0 to the wrong registry.  It's properly published now, sorry!

**Comment by ld0rman** [comment]
Thanks for your help. I have a more general question. How come the root DOM node is updated whenever anything happens in this form? I thought that the diff meant that only the bits of DOM that needed updating got updated.

**Comment by developit** [comment]
@ld0rman just figured it out! The `createComponent()` helper was overwriting `constructor` when setting the prototype, which made the parity check for high-order components fail.  The fix is just to add this on L23 of `util.js`:

```js
preactComponent.prototype.constructor = preactComponent;
```

Was tripping this logic to unmount a previously-rendered high order component when the newly rendered one differs:
https://github.com/developit/preact/blob/master/src/vdom/component.js#L119-L122

**Comment by ld0rman** [comment]
Oh right, probably should have used the es5 utility that you put in the using preact without Babel repo ha

**Comment by developit** [comment]
completely forgot I wrote that (am I getting old?)

**Pull request merged**
